//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactUsBackend.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class contact_usEntities11 : DbContext
    {
        public contact_usEntities11()
            : base("name=contact_usEntities11")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<brandsImage> brandsImages { get; set; }
        public virtual DbSet<contact> contacts { get; set; }
        public virtual DbSet<Register> Registers { get; set; }
    }
}
